version: "2.4"

services:
  subscan-api: &app_base
    image: scan/backend
    init: true
    build: .
    environment:
      MYSQL_HOST: mysql-subscan
      MYSQL_PASS: 'helloload'
      MYSQL_DB: 'subscan'
      REDIS_ADDR: redis:6379
      CHAIN_WS_ENDPOINT: 'ws://13.57.216.216:9944'
      NETWORK_NODE: 'crab'
      WEB_HOST: 'http://subscan-api:4399'
    ports:
      - '4399:4399'
    networks:
      - app_net
  subscan-daemon:
    <<: *app_base
    image: scan/backend
    ports: []
    command: ["python","run.py","substrate"]

networks:
  app_net:
    external: true
